[theme]
primaryColor = "#ff4b4b"             # 버튼/체크박스 포인트 색
backgroundColor = "#050814"          # 전체 배경
secondaryBackgroundColor = "#0b1220" # 카드/박스 배경
textColor = "#f9fafb"                # 기본 글자색
font = "sans serif"                  # 기본 폰트

[server]
headless = true

[browser]
gatherUsageStats = false
